import Head from "next/head";
import { Container } from "./styles";
import Footer from "../components/Footer";
import Form from "../components/Form";
import Navbar from "../components/Navbar";



export default function contact() {
  return (
    <Container>
    <Head>
        <title>Luanda Office Center</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,400;1,200;1,700&display=swap"
          rel="stylesheet"
        />
        <script src="https://maps.googleapis.com/maps/api/js?key=key"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar />
    <header>
      <h1>Entre em contato conosco</h1>
      <p>Tem Alguma questão nos envie agora uma mensagem!</p>
    </header>
        <main>
          <Form />
        </main>
        <Footer />
    </Container>
  )
}
