import Head from "next/head"
import Image from "next/image"

import { Container, Page, Card, Header } from "./styles"
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'


import Invesparso from '../../public/images/Invesparso.png'

export default function about() {
  return (
    
    <Container>
      <Head>
        <title>Luanda Office Center</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,400;1,200;1,700&display=swap"
          rel="stylesheet"
        />
        <script src="https://maps.googleapis.com/maps/api/js?key=key"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
    <Page>
      <main>
        <Header>
          <h1>Quem Somos</h1>
          <p>Sediada em Luanda pela empresa de direito Angolano Invesparso, a Luanda Office Center é uma empresa orientada para
            para o mercado empresarial angolano,  que cria e implementa soluções que visão potenciar as vendas e a notariedade de imagem das empresas
          </p>
        </Header>
          <Card>
          <h2>Empresa Mãe</h2>
          <div>
            <span>
        
              <p>
                A Invesparso é uma empresa criada para atender as necessidades de legalização de imóveis,
                aliados ao conhecimento e profissionalismo para gestão das informações e serviços, proporcionando
                aos clientes, facilidade, agilidade, comodidade e segurança nos procedimentos adequados á regularização de seu imóvel
              </p>
        
            </span>
            <span>
              <Image src={Invesparso} width="250" height="100" alt="Imagem da Invesparso" />
            </span>
          </div>
          </Card>
      </main>
    </Page> 
        <Footer />
     </Container>
  )
}
